In [164]:
import pandas as pd
import numpy as np

In [165]:
headers_tags = pd.read_excel('headers_tags.xlsx')
temp = pd.read_excel('headerandtag2.xlsx')
headers_tags = headers_tags.append(temp)

In [166]:
headers_tags_drop = headers_tags.dropna()
len(headers_tags_drop)

12541

In [167]:
headers_tags_drop = headers_tags_drop[headers_tags_drop['Tag'].str.contains('#') == True]
headers_tags_total = headers_tags_drop.copy()
len(headers_tags_drop)

12437

In [168]:
# Get rid of the customized tags, only work with the core attributes for now
headers_tags_drop = headers_tags_drop[headers_tags_drop['Tag'].str.contains('[x]_', regex = True) == False]

In [169]:
# Get rid of the extended tags, only work with the core attributes for now
headers_tags_drop['Tag'] = headers_tags_drop['Tag'].str.replace('\+.*', '')

In [170]:
headers_tags_drop['Tag'].nunique()

54

In [171]:
# number of occurance of each tag (core $ extended)

tag_frequency = headers_tags_drop['Tag'].value_counts().to_frame()
tag_frequency.columns = ['Count']
tag_frequency_total = headers_tags_total['Tag'].value_counts().to_frame()
tag_frequency_total.columns = ['Count']

In [191]:
headers_tags_simple = headers_tags[['Tag', 'Index']]
headers_tags_simple.head()

                  Tag  Index
0           #meta +id      0
1  #x_role +preferred      0
2       #x_definition      0
3                 NaN      0
4                 NaN      0

In [198]:
headers_tags_simple.loc[:, 'Index_within_file'] = headers_tags_simple.groupby('Index').cumcount()

/anaconda3/lib/python3.6/site-packages/pandas/core/indexing.py:517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [199]:
headers_tags_simple

                                   Tag  Index  Index_within_file
0                            #meta +id      0                  0
1                   #x_role +preferred      0                  1
2                        #x_definition      0                  2
3                                  NaN      0                  3
4                                  NaN      0                  4
5               #x_role +preferred +fr      0                  5
6               #x_role +preferred +es      0                  6
7                       #date +created      0                  7
8                       #date +updated      0                  8
9                       #meta +comment      0                  9
10                                Abia      1                  0
11                               NG001      1                  1
12                             3644714      1                  2
13                            #country      2                  0
14                             #status      2                  1
15                         #x_verified      2                  2
16                        #report_date      2                  3
17                             #loc_id      2                  4
18                                #loc      2                  5
19                            #loctype      2                  6
20                           #activity      2                  7
21                                #org      2                  8
22                         #x_capacity      2                  9
23                        #x_equipment      2                 10
24                            #x_staff      2                 11
25                          #x_doctors      2                 12
26                           #x_nurses      2                 13
27                        #x_isolation      2                 14
28                              #x_ppe      2                 15
29                     #x_burial_sites      2                 16
...                                ...    ...                ...
4387                        #date+year    977                  2
4388                         #affected    977                  3
4389                   #country+asylum    978                  0
4390                   #country+origin    978                  1
4391                        #date+year    978                  2
4392                         #affected    978                  3
4393                        #date+year    979                  0
4394                #country+residence    979                  1
4395                         #loc+name    979                  2
4396       #affected+f+children+age0_4    979                  3
4397      #affected+f+children+age5_11    979                  4
4398      #affected+f+children+age5_17    979                  5
4399  #affected+f+adolescents+age12_17    979                  6
4400       #affected+f+adults+age18_59    979                  7
4401     #affected+f+elderly+age60plus    979                  8
4402                 #affected+f+other    979                  9
4403                 #affected+f+total    979                 10
4404       #affected+m+children+age0_4    979                 11
4405      #affected+m+children+age5_11    979                 12
4406      #affected+m+children+age5_17    979                 13
4407  #affected+m+adolescents+age12_17    979                 14
4408       #affected+m+adults+age18_59    979                 15
4409     #affected+m+elderly+age60plus    979                 16
4410                 #affected+m+other    979                 17
4411                 #affected+m+total    979                 18
4412               #affected+all+total    979                 19
4413                   #country+asylum    980                  0
4414                   #country+origin    980                  1
4415                        #date+year    980                  2
4416                         #affected    980                  3

[13011 rows x 3 columns]